version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./public:/var/www/html
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env